/* Mock properties table. Built to be replaced with a mongoose model */
const properties = [
  {
    propertyid: 1,
    name: "The Grand Hotel",
    address: "123 Grand Street, Los Angeles, CA",
    rating: 4.5,
    capacity: 100,
    pricePerNight: 200,
    type: "Hotel",
  },
  {
    propertyid: 2,
    name: "Beautiful Beach House overlooking Miami Beach",
    address: "123 Ocean Drive, Miami, FL",
    rating: 4.8,
    capacity: 10,
    pricePerNight: 500,
    type: "Beach House",
  },
  {
    propertyid: 3,
    name: "Cozy Cabin in the Woods",
    address: "123 Forest Lane, Big Sur, CA",
    rating: 4.2,
    capacity: 6,
    pricePerNight: 150,
    type: "Cabin",
  },
  {
    propertyid: 4,
    name: "Luxury Condo in the Heart of the City",
    address: "123 Main Street, New York, NY",
    rating: 4.6,
    capacity: 4,
    pricePerNight: 300,
    type: "City Apartment",
  },
  {
    propertyid: 5,
    name: "Rustic Farmhouse with Stunning Views",
    address: "123 Country Road, Napa Valley, CA",
    rating: 4.4,
    capacity: 8,
    pricePerNight: 250,
    type: "Cabin",
  },
  {
    propertyid: 6,
    name: "Charming Cottage by the Lake",
    address: "123 Lakeview Drive, Lake Tahoe, CA",
    rating: 4.7,
    capacity: 4,
    pricePerNight: 175,
    type: "Cabin",
  },
  {
    propertyid: 7,
    name: "Modern Loft with Skyline Views",
    address: "123 Loft Avenue, Chicago, IL",
    rating: 4.5,
    capacity: 2,
    pricePerNight: 100,
    type: "City Apartment",
  },
  {
    propertyid: 8,
    name: "Lake House with Private Dock",
    address: "123 Lakeside Lane, Lake George, NY",
    rating: 4.9,
    capacity: 12,
    pricePerNight: 400,
    type: "Lake House",
  },
  {
    propertyid: 9,
    name: "Luxury Lakefront Retreat",
    address: "123 Lakeview Drive, Lake Tahoe, CA",
    rating: 4.8,
    capacity: 6,
    pricePerNight: 600,
    type: "Lake House",
  },
  {
    propertyid: 10,
    name: "Seaside Villa with Private Beach",
    address: "123 Beachfront Road, Malibu, CA",
    rating: 4.9,
    capacity: 8,
    pricePerNight: 800,
    type: "Beach House",
  },
  {
    propertyid: 11,
    name: "Lakefront Cabin with Mountain Views",
    address: "123 Mountain Lane, Lake Placid, NY",
    rating: 4.7,
    capacity: 4,
    pricePerNight: 350,
    type: "Lake House",
  },
  {
    propertyid: 12,
    name: "Beachfront Bungalow with Ocean Views",
    address: "123 Ocean Avenue, Honolulu, HI",
    rating: 4.6,
    capacity: 6,
    pricePerNight: 700,
    type: "Beach House",
  },
  {
    propertyid: 13,
    name: "Downtown Penthouse with Panoramic Views",
    address: "123 High Street, San Francisco, CA",
    rating: 4.9,
    capacity: 2,
    pricePerNight: 500,
    type: "City Apartment",
  },
  {
    propertyid: 14,
    name: "Modern Studio in the Heart of the City",
    address: "123 Urban Avenue, Seattle, WA",
    rating: 4.7,
    capacity: 2,
    pricePerNight: 300,
    type: "City Apartment",
  },
  {
    propertyid: 15,
    name: "Luxurious Resort on a Private Island",
    address: "123 Paradise Lane, Maldives",
    rating: 5.0,
    capacity: 200,
    pricePerNight: 1000,
    type: "Hotel",
  },
];

export default properties;
